# Managed by KUbuntu Migrate
# See: https://sw.kovidgoyal.net/kitty/open_actions/

# Open Markdown files directly with glow in a new kitty OS window.
protocol file
ext md,markdown
action launch --type=os-window -- glow -- $FILE_PATH

# Open ssh:// links with kitty's ssh kitten.
protocol ssh
action launch --type=os-window -- kitten ssh -- $URL
