# Managed by KUbuntu Migrate
#
# prefix + Ctrl-s: save current tmux sessions/windows/panes
# prefix + Ctrl-r: restore the last saved tmux environment

set -g history-limit 50000
set -g status on
set -g mouse off
set -g window-size latest

set -g @continuum-save-interval '1'
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell ~/.tmux/plugins/tmux-continuum/continuum.tmux
